id: I49DDD966
legacy_id: P000320
ocr_import_info:
  bdrc_scan_id: W22115
  source: bdrc
  ocr_info:
    timestamp: '2020-03-12T16:28:05'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T20:42:23.414414+00:00'
last_modified: 2022-09-02 04:42:31.507042
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22115
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW22115
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་ཐོར་བུ། བསྟན་འཛིན་ནོར་བུ།
  author: ཡོལ་མོ་སྤྲུལ་སྐུ ༠༣་བསྟན་འཛིན་ནོར་བུ།
statistics: null
quality: null
bases:
  I0877:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0877
      total_pages: 514
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I0877.txt
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
