id: I49DDD966
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-12T16:29:13+00:00'
last_modified: '2022-06-15T16:24:14.654513+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22115
  title: གསུང་ཐོར་བུ། བསྟན་འཛིན་ནོར་བུ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    3FF2:
      image_group_id: I0877
      title: ''
      total_pages: 514
      order: 1
      base_file: 3FF2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
